---
name: CI/CD for master
on:
  push:
    branches:
    - master
    - WIP
    paths:
    - 'cmake/**'
    - 'docker/**'
    - 'projects/**'
    - 'CMakeLists.txt'
    - 'xstartup'
jobs:
  build-linux:
    runs-on: [self-hosted, Linux]
    steps:
    - name: Checkout master
      uses: actions/checkout@master
      with:
        fetch-depth: 1

    - name: Build Linux docker image
      env:
        DOCKER_IMAGE_NAME: ultimaker/cura-build-environment
        DOCKER_IMAGE_LATEST_TAG: latest
        GIT_REF: ${{ github.ref }}
        DOCKER_IO: docker.io
        DOCKER_USER: ${{ secrets.DOCKERUSERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERPASSWORD }}
      run: .github/workflows/build-linux.sh

  build-windows:
    runs-on: [self-hosted, Windows]
    steps:
    - name: Checkout master
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Build Windows docker image
      env:
        DOCKER_IMAGE_NAME: ultimaker/cura-build-environment
        DOCKER_IMAGE_LATEST_TAG: win1809-latest
        GIT_REF: ${{ github.ref }}
        DOCKER_IO: docker.io
        DOCKER_USER: ${{ secrets.DOCKERUSERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERPASSWORD }}
      run: .github/workflows/build.ps1

  build-macOS:
    runs-on: [self-hosted, macos, Catalina]
    steps:
    - name: Checkout master
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Build the environment on macOS
      run: .github/workflows/build-macOS.sh

